version: '3.1'


services:
  solar_energy_system_pg:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
