version: '3.1'


services:
  solar_energy_system_pg:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Authorised users only!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
      - 5050:80

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGO_PORT:-27017}:27017
