version: '3.1'


services:
  solar_energy_system_pg:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:-5432}:5432

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - ${MONGO_PORT:-27017}:27017
